compile: CodeWriter.java SourceReader.java YetiParser.java YetiType.java\
         YetiCode.java YetiC.java CompileException.java YetiTypeAttr.java\
         YetiBuiltins.java JavaType.java JavaExpr.java
	javac -source 1.4 -target 1.4 -d .. -classpath ../asm-3.1.jar:.. $+

