JAVAC=javac

lib: Core.java Fun.java Hash.java Tag.java TagCon.java Struct.java\
     Num.java IntNum.java BigNum.java RatNum.java FloatNum.java\
     AIter.java AList.java LList.java MList.java ByKey.java\
     NoSuchKeyException.java
	$(JAVAC) -d .. $+
