JAVAC=javac

lib: Core.java Fun.java Hash.java Tag.java TagCon.java Struct.java\
     Num.java IntNum.java BigNum.java RatNum.java FloatNum.java\
     AIter.java AList.java LList.java MList.java ByKey.java\
     NoSuchKeyException.java ListRange.java MapList.java FunX.java\
     FilterList.java BinFun.java Compose.java Selector.java\
     Selectors.java Bind2nd.java ListIter.java Like.java Match.java\
	 LazyList.java Map2List.java
	$(JAVAC) -source 1.4 -target 1.4 -d .. $+
